// ⚠️ GENERATED by build.ts from extensions/lib/harness/*/ — DO NOT EDIT.
// Regenerated on every build/prepare. Add a harness by creating
// extensions/lib/harness/<id>/{discovery,parse}.ts — this table picks it up.

import type { HarnessDiscovery, HarnessParseAdapter } from "./types.ts";
import { discovery as claudeCodeDiscovery } from "./claude-code/discovery.ts";
import { parse as claudeCodeParse } from "./claude-code/parse.ts";
import { discovery as piDiscovery } from "./pi/discovery.ts";
import { parse as piParse } from "./pi/parse.ts";

/** Built-in harnesses, keyed by id (= directory name). */
export const BUILTIN_HARNESSES: Record<string, { discovery: HarnessDiscovery; parse: HarnessParseAdapter }> = {
	"claude-code": { discovery: claudeCodeDiscovery, parse: claudeCodeParse },
	"pi": { discovery: piDiscovery, parse: piParse },
};
